<a href="https://colab.research.google.com/github/vkjadon/introduction-to-deep-learning/blob/main/02C-pythonForDeepLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Library

<font color="brown">NumPy stands for “Numerical Python”.</font>  

It is a tool suited for array oriented computing efficiently.

The “numpy array” uses less memory than python list and also the execution time is faster.   

The internal type of numpy array is “ndarray”. 

$A_{m,n} =\begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1} & a_{m,2} & \cdots & a_{m,n}
 \end{pmatrix}$  

We start by importing the NumPy library.

In [3]:
# Import the NumPy library
import numpy as np

In deep learning, we often work with large datasets. NumPy arrays provide efficient storage and manipulation of numerical data, making them a fundamental building block.  
Let us create a two-dimensional NumPy array.

In [9]:
# Matrix of 4 Rows and 3 Columns :
#In NumPy, this 2D matrix has Two axes
#First axis length is 4 and Second axis length is 3 (4L,3L) 

matrixA = np.array([(1,2,3),(4,5,6),(7,2,3),(4,5,6)])
print(matrixA)
print('Shape of Matrix', matrixA.shape)
print('Dimension of Matrix', matrixA.ndim)
print("Type of matrixA ", type(matrixA))

[[1 2 3]
 [4 5 6]
 [7 2 3]
 [4 5 6]]
Shape of Matrix (4, 3)
Dimension of Matrix 2
Type of matrixA  <class 'numpy.ndarray'>


In [21]:
#matrixA.T
#matrixA
matrixA.reshape(6,-1)
#matrixA.reshape(3,2,-1)
#matrixA.reshape(3,4)
#matrixA.shape 
#matrixA

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 2],
       [3, 4],
       [5, 6]])

You can reshape the matrixA using the reshape() function in NumPy. Reshaping allows you to change the shape or dimensions of an array while maintaining the same number of elements. So, we can reshape the 'matrixA' into another matrix of the total numebr of elements. Otherwise, it will throw an error. We can specify one dimension by '-1' for the unknown shape. The Numpy will compute the that on its own if exists.

We can access elements of the array using indexing, just like in regular Python lists.

In [30]:
# Access elements of the array
print("First matrix:", matrixA)
print("First element:", matrixA[0])
print("Last element:", matrixA[-1])

First matrix: [[1 2 3]
 [4 5 6]
 [7 2 3]
 [4 5 6]]
First element: [1 2 3]
Last element: [4 5 6]
Slice of the array: [[1 2 3]
 [4 5 6]]


In [34]:
# Access elements of the array
print("First element:", matrixA[1,0])
print("Last element:", matrixA[2,-1])

First element: 4
Last element: 3
Slice of the array: [5 6]
Slice of the array: [5]
Slice of the array: [5 6]


# Slicing (Colon Operator)
['start' : 'end': 'step'] for 1D array.  
`start` is inclusive and `end` is exclusive 

In [ ]:
x = np.array([18, 2, 5, 3, 20])
x[3:] #All after index 3. x[3]=, x[4]=20 # x[3] is Inclusive 
x[:4] #All before index 4. x[0]=18, x[1]=2, x[2]=5, x[3]=3 # x[4] Exclusive

** 2D array**
['start' : 'end': 'step' , 'start' : 'end': 'step' ] for 2D array.  
`start` is inclusive and `end` is exclusive 

In [37]:
print("Slice of the array:", matrixA[0:2])
# print("Slice of the array:", matrixA[2:2])
print("Slice of the array:", matrixA[1, 1:3])
print("Slice of the array:", matrixA[1, 1:-1])
print("Slice of the array:", matrixA[1, 1:8]) # No error

Slice of the array: [[1 2 3]
 [4 5 6]]
Slice of the array: [5 6]
Slice of the array: [5]
Slice of the array: [5 6]


# Creating a NumPy array – arange

`arange([start,] stop[, step], [, dtype=None])`  

**arange** returns evenly spaced values within a given interval starting from first optional parameter and within the `stop` value.  
If only one parameter is given, it is assumed as `stop` and the `start` is automatically set to 0.  
If the `step` is not given, it is set to `1` but if `step` is given, the `start` parameter cannot be optional, i.e. it has to be given as well.  
The `step` sets the spacing between two adjacent values of the output array.

In [42]:
dayTemperature=np.arange(6)
#Gives 6 values starting from 0 and default interval of 1
print(dayTemperature)

[0 1 2 3 4 5]


In [ ]:
dayTemperature=np.arange(6,12, 1)
#First Value is 22 and it stops at 30, So 30 is not included
print(dayTemperature)

In [ ]:
dayTemperature=np.arange(5.3)
#First Value is 0 and it gives output 25 with default interval of 1
print(dayTemperature)

# Creating a NumPy array – linspace


`linspace(start, stop, num=50, endpoint=True, retstep=False)`  

<font color='brown'>create NumPy array using linspacebar</font>

Array of linearly spaced values defined by `num` including `start` and `stop`  

<font color='brown'>default value of num is 50</font>

In [ ]:
dayTemperature=np.linspace(20,30,11)
print(dayTemperature)

In [ ]:
dayTemperature, spacing=np.linspace(20,30,11,  endpoint=True, retstep=True)
print(dayTemperature, spacing)

In [43]:
A=np.arange(12).reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

# Creating a NumPy Array - Using Random

Use `np.random.rand` to create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [ ]:
A=np.random.rand(4,3)*100
A

Use `np.random.randn` to generates an array of given shape, filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1.

In [ ]:
A=np.random.randn(12).reshape(4,3)
A

#Dot Product or Inner Product

Consider random arrays of shape `a(4,3)` and `b(3,2)`. 
`np.dot(a, b)` has shape equal to number of rows of `a`, number of columns of `b` 

- In numpy the `*` operator indicates element-wise multiplication and is different from `np.dot`. 

- Dot Product is also known as inner product

In [ ]:
#a=np.random.randn(4,3)
a=np.random.randn(3,2)
b=np.random.randn(3,2)
c=a*b
print(c)

<span style="color:blue;">To perform element-wise multiplication, the dimension of both the arrays must be the same.</span>

<span style="color:brown">The other method is broadcating.</span>

In [ ]:
a=np.arange(12).reshape(4,3)
b=np.arange(10,22).reshape(4,3)
c=a*b
print(c)

In [ ]:
a=np.random.randn(256,15)
b=np.random.randn(15,5)
c=np.dot(a,b)
c.shape

To perform `dot product` on two muti-dimension arrays, the last dimension of the first array should be equal to last but one dimension of second array. So check `a.shape[-1]==b.shape[-2]`

In [ ]:
print(a.shape[-1], b.shape[-2])
a.shape[-1] == b.shape[-2]

In [ ]:
a=np.random.randn(256,15)
b=np.random.randn(15,5)
if(a.shape[1] == b.shape[0]):
  c=np.dot(a,b)
  c.shape
  print(c)
else:
  print("The columns and rows condition not satisfied")

In [ ]:
a=np.random.randn(3,4)
b=np.random.randn(4,1)
c=a+b.T
print("Shape of a+b.T ",c.shape)
c=a.T+b
print("Shape of a.T+b ",c.shape)

In [ ]:
a=np.random.randn(3,3)
b=np.random.randn(3,1)
c=a*b
print(c)

if x is a vector, then a Python operation such as $s = x + 3$ or $s = \frac{1}{x}$ will output s as a vector of the same size as x.

In [ ]:
print(a)
b=a+3
print(b)
b=b*7
print(b)

Create an array corresponding to `(px_x*px_y*3)` and reshape to `(px_x, px_y,3)` and use `image.shape[0]`, `image.shape[1]` and `image.shape[2]`  

We can also use `image.reshape(-1,1)` for arranging all elements in a column vector. `-1` represnt unknown rows.  

We can also use `(1,-1)` for unknown columns and one row if required. 

In [ ]:
a=np.random.randn(4*4*3)
image=a.reshape(4,4,3)
image.shape[0]
image.reshape(-1,1)

In [ ]:
image.reshape(1,-1)

In [ ]:
a=np.array([[1,4, 5],[3,5,8]])  
b=np.sum(a,axis=1)  # 0 is column and 1 is row
b  

# Sigmoid Function

Implement `np.exp()` and `math.exp()` for the sigmoid function and compare.  

$$sigmoid(x) = \frac{1}{1+e^{-x}}$$

- It takes an input value x and outputs a value between 0 and 1, which can be interpreted as a probability.
- The function has an S-shaped curve, mapping the input values to a smooth, non-linear range.
- The sigmoid function is commonly used in the last layer of a binary classification task, where the output represents the probability of belonging to a certain class.

In [40]:
import math

In [41]:
def sigmoid(z):
  return 1/(1+math.exp(-z))
sigmoid(1)

0.7310585786300049

<span style="color:brown"> **Cannot pass array as an arguement**</span>  

Give it a try to pass array to find sigmoid function of all the array elements.

In [ ]:
a=np.array([1,2,3])
sigmoid(a)

In [1]:
def sigmoid(z):
  return 1/(1+np.exp(-z))

In [4]:
# Example usage
x = np.array([-1, 0, 1])
output = sigmoid(x)
print(output)

[0.26894142 0.5        0.73105858]


In [ ]:
w = np.array([[0.1124579], [0.23106775]])
b = -0.3
X = np.array([[1., -1.1, -3.2],[1.2, 2., 0.1]])
A=sigmoid(np.dot(w.T,X)+b)
print(A)

[[0.52241976 0.50960677 0.34597965]]


#ReLU (Rectified Linear Unit)

- It takes an input value x and returns x if it is positive, and 0 otherwise.
- The ReLU function introduces non-linearity to the network by mapping negative values to 0, while leaving positive values unchanged.
- ReLU is a popular choice due to its simplicity and ability to mitigate the vanishing gradient problem.

In [5]:
def relu(x):
    return np.maximum(0, x)

In [6]:
# Example 
x = np.array([-1, 0, 1])
output = relu(x)
print(output)

[0 0 1]


#Loss Functions

Mean Squared Error (MSE) Loss Function:  
- The Mean Squared Error (MSE) loss function is widely used for regression problems.
- It calculates the average squared difference between the predicted values and the true values.
- For a set of m predictions $y_{pred}$ and corresponding true values $y_{true}$, the MSE loss is computed as:

$$L_{mse}(\hat{y},y) = \sum_{i=0}^{m-1}(y^{(i)} - \hat{y}^{(i)})^2$$

- The MSE loss penalizes larger errors more than smaller errors due to the squaring operation.
- Minimizing the MSE loss encourages the model to produce predictions that are closer to the true values.

In [7]:
def mse_loss(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2)

In [8]:
# Example usage
y_true = np.array([1, 2, 3])
y_pred = np.array([1.5, 2.2, 2.8])
loss = mse_loss(y_true, y_pred)
print(loss)

0.11000000000000006


# Cost Function

Implement the numpy vectorized version of the L2 loss. There are several way of implementing the L2 loss but you may find the function np.dot() useful. As a reminder, if $x = [x_1, x_2, ..., x_n]$, then `np.dot(x,x)` = $\sum_{j=0}^n x_j^{2}$. 

- L2 loss is defined as $$\begin{align*} & L_2(\hat{y},y) = \sum_{i=0}^{m-1}(y^{(i)} - \hat{y}^{(i)})^2 \end{align*}\tag{7}$$

In [ ]:
def L2(yhat, y):    
    loss = np.dot(abs(y-yhat).T, abs(y-yhat))
    return loss

In [ ]:
yhat = np.array([.9, 0.2, 0.1, .4, .9]).reshape(5,1)
y = np.array([1, 0, 0, 1, 1]).reshape(5,1)
print(yhat.shape, y.shape)
print("L2 = " + str(L2(yhat, y)))

(5, 1) (5, 1)
L2 = [[0.43]]


# Softmax and Normalization

Row Normalization is done by dividing each element of row of a given vector x by its norm based on row.  

It is changing x to $ \frac{x}{\| x\|} $.  

We get a column vector of norm if we take the square root of the sum of squares of each row elements. Then divide each row by its norm to normalize rows.


$$\| x\| = \text{np.linalg.norm(x, axis=1, keepdims=True)}$$  

With `keepdims=True` the result will broadcast correctly against the original x.

`axis=1` means you are going to get the norm in a row-wise manner. If you need the norm in a column-wise way, you would need to set `axis=0`. 

In [38]:
x = np.array([[0, 3, 4],
              [1, 6, 4]])
x_norm=np.linalg.norm(x, axis=1, keepdims=True)
x=x/x_norm
print("Norm ", x_norm, "\nnormalizeRows(x) = ", x)

Norm  [[5.        ]
 [7.28010989]] 
normalizeRows(x) =  [[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]


In [ ]:
def softmax(x):
    x_exp=np.exp(x)
    x_sum=np.sum(x_exp, axis=1).reshape(x.shape[0],1)
    s=x_exp/x_sum    
    return s

In [ ]:
x = np.array([[9, 2, 5, 0, 0],
                [7, 5, 0, 0 ,0]])
s=softmax(x)
print(s)

[[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]


# np.sum()

In [ ]:
x = np.array([[9, 2, 5, 3, 10], [7, 5, 10, 2 ,6], [17, 1, 10, 20 ,10]])
print(x)

[[ 9  2  5  3 10]
 [ 7  5 10  2  6]
 [17  1 10 20 10]]


In [ ]:
sum=x.sum(axis=0)
# equivalent to sum=np.sum(x,axis=0)
sum

array([33,  8, 25, 25, 26])

# Broadcasting Example

In [ ]:
percent=100*x/sum
print(percent)

[[27.27272727 25.         20.         12.         38.46153846]
 [21.21212121 62.5        40.          8.         23.07692308]
 [51.51515152 12.5        40.         80.         38.46153846]]


In [ ]:
x = np.array([18, 2, 5, 3, 20]).reshape(5,1)
y = np.array([9, 14, 15, 3, -200]).reshape(5,1)
z=100*(abs(y-x))/x
print(z)

[[  50.]
 [ 600.]
 [ 200.]
 [   0.]
 [1100.]]


# Numpy array to Pandas DataFrame

In [ ]:
import pandas as pd
df = pd.DataFrame(percent)

print(df)
print(type(df))

           0     1     2     3          4
0  27.272727  25.0  20.0  12.0  38.461538
1  21.212121  62.5  40.0   8.0  23.076923
2  51.515152  12.5  40.0  80.0  38.461538
<class 'pandas.core.frame.DataFrame'>


In [ ]:
print(percent)

[[27.27272727 25.         20.         12.         38.46153846]
 [21.21212121 62.5        40.          8.         23.07692308]
 [51.51515152 12.5        40.         80.         38.46153846]]


In [ ]:
percent[:] # All rows and all columns

array([[27.27272727, 25.        , 20.        , 12.        , 38.46153846],
       [21.21212121, 62.5       , 40.        ,  8.        , 23.07692308],
       [51.51515152, 12.5       , 40.        , 80.        , 38.46153846]])

In [ ]:
percent[:,1:3] #All rows and columns as specified

array([[25. , 20. ],
       [62.5, 40. ],
       [12.5, 40. ]])

In [ ]:
percent[1:3,2:4] # Row at index 1 and 2 and column at index 2 and 3.

array([[40.,  8.],
       [40., 80.]])