<a href="https://colab.research.google.com/github/vkjadon/introduction-to-deep-learning/blob/main/02C-pythonForDeepLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
from IPython.display import Image

In [ ]:
import numpy as np
import math

## Sigmoid Function

Implement `np.exp()` and `math.exp()` for the sigmoid function and compare.  

$$sigmoid(x) = \frac{1}{1+e^{-x}}$$  

<!-- <img src="images/Sigmoid.png" style="width:500px;height:228px;text-align:center"> -->



In [ ]:
def sigmoid(z):
  return 1/(1+math.exp(-z))
sigmoid(1)

0.7310585786300049

<span style="color:brown"> **Cannot pass array as an arguement**</span>  

Give it a try to pass array to find sigmoid function of all the array elements.

In [ ]:
a=np.array([1,2,3])
sigmoid(a)

TypeError: ignored

In [ ]:
def sigmoid(z):
  return 1/(1+np.exp(-z))
sigmoid(1)

0.7310585786300049

In [ ]:
a=np.array([1,2,3])
sigmoid(a)

array([0.73105858, 0.88079708, 0.95257413])

In [ ]:
w = np.array([[0.1124579], [0.23106775]])
b = -0.3
X = np.array([[1., -1.1, -3.2],[1.2, 2., 0.1]])
A=sigmoid(np.dot(w.T,X)+b)
print(A)

[[0.52241976 0.50960677 0.34597965]]


## Softmax and Normalization

Row Normalization is done by dividing each element of row of a given vector x by its norm based on row.  

It is changing x to $ \frac{x}{\| x\|} $.  

We get a column vector of norm if we take the square root of the sum of squares of each row elements. Then divide each row by its norm to normalize rows.


$$\| x\| = \text{np.linalg.norm(x, axis=1, keepdims=True)}$$  

With `keepdims=True` the result will broadcast correctly against the original x.

`axis=1` means you are going to get the norm in a row-wise manner. If you need the norm in a column-wise way, you would need to set `axis=0`. 

In [ ]:
x = np.array([[0, 3, 4],
              [1, 6, 4]])
x_norm=np.linalg.norm(x, axis=1, keepdims=True)
x=x/x_norm
print("Norm ", x_norm, "\nnormalizeRows(x) = ", x)

Norm  [[5.        ]
 [7.28010989]] 
normalizeRows(x) =  [[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]


In [ ]:
def softmax(x):
    x_exp=np.exp(x)
    x_sum=np.sum(x_exp, axis=1).reshape(x.shape[0],1)
    s=x_exp/x_sum    
    return s

In [ ]:
x = np.array([[9, 2, 5, 0, 0],
                [7, 5, 0, 0 ,0]])
s=softmax(x)
print(s)

[[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]


## Cost Function

Implement the numpy vectorized version of the L2 loss. There are several way of implementing the L2 loss but you may find the function np.dot() useful. As a reminder, if $x = [x_1, x_2, ..., x_n]$, then `np.dot(x,x)` = $\sum_{j=0}^n x_j^{2}$. 

- L2 loss is defined as $$\begin{align*} & L_2(\hat{y},y) = \sum_{i=0}^{m-1}(y^{(i)} - \hat{y}^{(i)})^2 \end{align*}\tag{7}$$

In [ ]:
def L2(yhat, y):    
    loss = np.dot(abs(y-yhat).T, abs(y-yhat))
    return loss

In [ ]:
yhat = np.array([.9, 0.2, 0.1, .4, .9]).reshape(5,1)
y = np.array([1, 0, 0, 1, 1]).reshape(5,1)
print(yhat.shape, y.shape)
print("L2 = " + str(L2(yhat, y)))

(5, 1) (5, 1)
L2 = [[0.43]]


## np.sum()

In [ ]:
x = np.array([[9, 2, 5, 3, 10], [7, 5, 10, 2 ,6], [17, 1, 10, 20 ,10]])
print(x)

[[ 9  2  5  3 10]
 [ 7  5 10  2  6]
 [17  1 10 20 10]]


In [ ]:
sum=x.sum(axis=0)
# equivalent to sum=np.sum(x,axis=0)
sum

array([33,  8, 25, 25, 26])

## Broadcasting Example

In [ ]:
percent=100*x/sum
print(percent)

[[27.27272727 25.         20.         12.         38.46153846]
 [21.21212121 62.5        40.          8.         23.07692308]
 [51.51515152 12.5        40.         80.         38.46153846]]


In [ ]:
x = np.array([18, 2, 5, 3, 20]).reshape(5,1)
y = np.array([9, 14, 15, 3, -200]).reshape(5,1)
z=100*(abs(y-x))/x
print(z)

[[  50.]
 [ 600.]
 [ 200.]
 [   0.]
 [1100.]]


## Numpy array to Pandas DataFrame

In [ ]:
import pandas as pd
df = pd.DataFrame(percent)

print(df)
print(type(df))

           0     1     2     3          4
0  27.272727  25.0  20.0  12.0  38.461538
1  21.212121  62.5  40.0   8.0  23.076923
2  51.515152  12.5  40.0  80.0  38.461538
<class 'pandas.core.frame.DataFrame'>


## Slicing (Colon Operator)
['start' : 'end': 'step'] for 1D array.  
`start` is inclusive and `end` is exclusive 

In [ ]:
x = np.array([18, 2, 5, 3, 20])

In [ ]:
x[3:] #All after index 3. x[3]=, x[4]=20 # x[3] is Inclusive 

array([ 3, 20])

In [ ]:
x[:4] #All before index 4. x[0]=18, x[1]=2, x[2]=5, x[3]=3 # x[4] Exclusive

array([18,  2,  5,  3])

** 2D array**
['start' : 'end': 'step' , 'start' : 'end': 'step' ] for 2D array.  
`start` is inclusive and `end` is exclusive 

In [ ]:
print(percent)

[[27.27272727 25.         20.         12.         38.46153846]
 [21.21212121 62.5        40.          8.         23.07692308]
 [51.51515152 12.5        40.         80.         38.46153846]]


In [ ]:
percent[:] # All rows and all columns

array([[27.27272727, 25.        , 20.        , 12.        , 38.46153846],
       [21.21212121, 62.5       , 40.        ,  8.        , 23.07692308],
       [51.51515152, 12.5       , 40.        , 80.        , 38.46153846]])

In [ ]:
percent[:,1:3] #All rows and columns as specified

array([[25. , 20. ],
       [62.5, 40. ],
       [12.5, 40. ]])

In [ ]:
percent[1:3,2:4] # Row at index 1 and 2 and column at index 2 and 3.

array([[40.,  8.],
       [40., 80.]])