<a href="https://colab.research.google.com/github/vkjadon/introduction-to-deep-learning/blob/main/02pythonForDeepLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Python for Deep Learning : NumPy Library

Welcome to the session on "Python for Deep Learning". Deep Learning delas with huge data and NumPy is a very powerful and popular Python library. We will discuss various capabilities of NumPy in this session using the Google Colaboratory online resource for writting the Python Code.
Lets get started!

- Open the Google Coab using Google Search

# Matrix Fundamentals

<font color="brown">NumPy stands for “Numerical Python”.</font>

It is a tool suited for array oriented computing efficiently.

The “numpy array” uses less memory than python list and also the execution time is faster.

The internal type of numpy array is “ndarray”.

$A_{m,n} =\begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1} & a_{m,2} & \cdots & a_{m,n}
 \end{pmatrix}$

- The shape of this matrix is $m \times n$

- The $i, j$ are the indices used to indicate an element; where $i=1$ to $m$ and $j=1$ to $n$

- We start by importing the NumPy library

## Assigning Array

In [2]:
# Import the NumPy library
import numpy as np

In deep learning, we often work with large datasets. NumPy arrays provide efficient storage and manipulation of numerical data.
Let us create a two-dimensional NumPy array.

In [181]:
#1D array of 3 elements
arr1D3E = np.array([(1,2,3)])
#In NumPy, this 2D matrix has Two axes
#First axis length is 2 and Second axis length is 3 (2L,3L)
arr2D23 = np.array([(1,2,3),(4,5,6)])

In [ ]:
print(arr1D3E)
print("Type of 1D Array arr1D3E ", type(arr1D3E))
print('Shape of 1D Array arr1D3E', arr1D3E.shape)
print('Size of 1D Array arr1D3E', arr1D3E.size)
print('Dimension of 1D Array arr1D3E', arr1D3E.ndim)
print("Type of data of elements of 1D Array arr1D3E ", arr1D3E.dtype)

In [ ]:
print(arr2D23)
print("Type of 2D Array arr2D23 ", type(arr2D23))
print('Shape of 2D Array arr2D23', arr2D23.shape)
print('Size of 2D Array arr2D23', arr2D23.size)
print('Dimension of 2D Array arr2D23', arr2D23.ndim)
print("Type of data of elements of 2D Array arr2D23 ", arr2D23.dtype)

We can see there are two arrays of size 3 in the outer array. This understanding will help to understand the 3D arrays.

##Reshaping Matrices

You can reshape the matrixA using the reshape() function in NumPy. Reshaping allows you to change the shape or dimensions of an array while maintaining the same number of elements. So, we can reshape the 'matrixA' into another matrix of equal total numebr of elements. Otherwise, it will throw an error. We can specify one dimension by '-1' for the unknown shape. The Numpy will compute that on its own if exists.
- We can use `.T` to transpose the matrix.

In [ ]:
#arr2D23.T
#arr2D23
arr2D23.reshape(6,-1)
#arr2D23.reshape(3,2,-1)
#arr2D23.reshape(3,4)
#arr2D23.shape
#arr2D23

##Accessing Array Elements

We can access elements of the array using indexing, just like in regular Python lists.

In [ ]:
# Access elements of the array
print("First matrix:", arr2D23)
print("First element:", arr2D23[0])
print("Last element:", arr2D23[-1])

In [ ]:
# Access elements of the array
print("First element:", arr2D23[0,0], "\nLast element:", arr2D23[1,-1])

# Creating a NumPy array

 ## arange() function

`arange([start,] stop[, step], [, dtype=None])`

**arange** returns evenly spaced values within a given interval starting from first optional parameter and within the `stop` value.
If only one parameter is given, it is assumed as `stop` and the `start` is automatically set to 0.
If the `step` is not given, it is set to `1` but if `step` is given, the `start` parameter cannot be optional, i.e. it has to be given as well.
The `step` sets the spacing between two adjacent values of the output array.

In [ ]:
dayTemperature=np.arange(6)
#Gives 6 values starting from 0 and default interval of 1
print(dayTemperature)

In [ ]:
dayTemperature=np.arange(22,30,1)
#First Value is 22 and it stops at 30, So 30 is not included
print(dayTemperature)

In [ ]:
dayTemperature=np.arange(25)
#First Value is 0 and it gives 25 output with default interval of 1
print(dayTemperature)

In [ ]:
np.arange(12).reshape(4,3)

##linspace() Function


`linspace(start, stop, num=50, endpoint=True, retstep=False)`

<font color='brown'>create NumPy array using linspacebar</font>

Array of linearly spaced values defined by `num` including `start` and `stop`

<font color='brown'>default value of num is 50</font>

In [ ]:
dayTemperature=np.linspace(20,30,11)
print(dayTemperature)

In [ ]:
dayTemperature, spacing=np.linspace(20,30, 20, endpoint=True, retstep=True)
print(dayTemperature, spacing)

##Random Functions

Use `np.random.rand` to create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [ ]:
np.random.rand(4,2)

We can multiply by a factor if we wand higher magnitude. For example, if we need random number up to 255, we can do so as below:

In [ ]:
np.random.rand(4,2)*255

Use `np.random.randn` to generates an array of given shape, filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1.

In [ ]:
np.random.randn(3,4)

In [163]:
np.random.randint(3,6)

5

In [164]:
np.random.randint(3,6, size=(2,4))

array([[3, 3, 5, 5],
       [4, 4, 3, 5]])

##Zeros, Ones and Full

In [ ]:
np.zeros((3,3,2))

In [ ]:
np.ones((3,2,4))

In [ ]:
np.full((2,3,4),4)

#Matrix Operations

##Element wise Multiplication

- In NumPy the `*` operator indicates element-wise multiplication and is different from `np.dot`.

- Dot Product is also known as inner product

In [186]:
#a=np.random.randn(4,3)
a=np.random.randn(3,2)
b=np.random.randn(3,2)
mult=np.multiply(a,b)
add=np.add(a,b)
sub=np.subtract(a,b)
div=np.divide(a,b)

In [ ]:
mult

- To perform element-wise multiplication, the dimension of both the arrays must be the same.
- The otherwise the broadcating can be used.

##Arithmatic Functions

In [ ]:
np.sqrt(abs(np.exp(a)))

In [ ]:
np.log(abs(np.power(a,3)))

In [ ]:
np.min(a)

In [ ]:
np.mean(a)

In [ ]:
np.max(a)

##append() and insert()

In [ ]:
ones=np.ones(5, dtype='int8')
print(ones)

In [ ]:
np.append(ones,[2,4])

In [ ]:
np.insert(ones, 3, [4,3]) #inserted at the index specified

##Dot Product or Inner Product

- Consider random arrays of shape `a(4,3)` and `b(3,2)`.
`np.dot(a, b)` has shape equal to number of rows of `a`, number of columns of `b`

- To perform `dot product` on two muti-dimension arrays, the last dimension of the first array should be equal to last but one dimension of second array. So check `a.shape[-1]==b.shape[-2]`

In [95]:
a=np.random.randn(256,15)
b=np.random.randn(15,5)

In [96]:
print(a.shape[-1], b.shape[-2])
a.shape[-1] == b.shape[-2]

15 15


True

In [ ]:
if(a.shape[1] == b.shape[0]):
  c=np.dot(a,b)
  c.shape
  print(c)
else:
  print("The columns and rows condition not satisfied")

Broadcasting

In [114]:
a=np.random.randn(3,3)
b=np.random.randn(3,1)
cNP=np.multiply(a,b)
c=a*b
cDot=np.dot(a,b)
print(c,cNP, cDot)

[[-0.99828638 -0.4331056  -0.04600756]
 [-0.25578499  0.11197988 -0.31575506]
 [-0.05607391  0.25142116  0.1169518 ]] [[-0.99828638 -0.4331056  -0.04600756]
 [-0.25578499  0.11197988 -0.31575506]
 [-0.05607391  0.25142116  0.1169518 ]] [[-0.53627186]
 [ 0.52531337]
 [-0.3859096 ]]


In [ ]:
a=np.random.rand(10).reshape(10,1)
b=np.random.rand(10).reshape(1,10)
cDot=np.dot(a,b)
print(cDot)

##Slicing


**Colon Operator**.

Slicing is used to take desired elements of an array starting from one given index to another given index.

`[start : end: step]` for 1D array.

- **`start`** is inclusive and **`end`** is exclusive

- If we don't pass `start` its considered 0

- If we don't pass end its considered length of array in that dimension

- If we don't pass `step` its considered 1

In [ ]:
x = np.array([18, 2, 5, 3, 20])
print(x[3:]) #All after index 3. x[3]=3, x[4]=20 # x[3] is Inclusive
print(x[:4]) #All before index 4. x[0]=18, x[1]=2, x[2]=5, x[3]=3 # x[4] Exclusive

We use [`start` : `end`: `step` , `start` : `end`: `step` ] for 2D array.

In [ ]:
array2D=np.random.rand(4,3)
array2D

In [ ]:
print("Slice of the array:", array2D[0:2]) #check Shape
print("Slice of the array:", array2D[1, 1:3])
print("Slice of the array:", array2D[2, 1:-1])

In [ ]:
array2D>0.3

In [ ]:
array2D[array2D>0.3]

In [ ]:
np.where(array2D>0.3, array2D, 0)

#Handling Image Data (3D Matrix)

Color images are represented by 3D array corresponding to pixels in width, pixels in height for each of RGB channel. and reshape to a row or column matrix as below.

In [91]:
randA=np.random.rand(64*64*3)*255

In [ ]:
image=randA.reshape(64,64,3)
image = image.astype('uint8')
image

In [ ]:
import matplotlib.pyplot as plt
imgplot = plt.imshow(image)

This represent an color image of $64 \times 64$ and is stored in array of size (64, 64, 3). The last 3 represent the R, G and B channels. If you observe the `Image` matrix, you can see there are three elements in one/inner array. There are 64 such lines of arrays. These 64 lines of arrays of 3 elemets are further appearing 64 times to complete the `Image` matrix. In `Deep Learning` applications handling images, we call each pixel values as features and need to be converted to a column vector.

In [ ]:
print(image.shape[0])

In [ ]:
print(image[0]) #Check shape

In [ ]:
print(image[0][0]) #Check shape

In [ ]:
print(image[0][0][0]) #Check shape

In [ ]:
image.reshape(-1,1)

In [ ]:
image.reshape(1,-1)

In [ ]:
image

#Mathematical Functions

##Commonly Used Functions


$$y=f(x)$$
- Linear Function
$$f(x) = wx+b$$
$$f(x) = max(0,x)$$
- Quadratic Function
$$f(x) = 4ax^2+b$$
- Exponential Function
$$f(x) = \frac{1}{1+e^{-x}}$$

$$f(x_i) = \frac {e^{x_i}}{\sum_{j=1}^C{e^{x_j}}}$$

- Trignometric Function
$$f(x) = tan^{-1}(x)$$
- Logrithmic Function
$$f(x) = log(x)$$

## Sigmoid Function

Implement `np.exp()` and `math.exp()` for the sigmoid function and compare.

$$sigmoid(x) = \frac{1}{1+e^{-x}}$$

- It takes an input value x and outputs a value between 0 and 1, which can be interpreted as a probability.
- The function has an S-shaped curve, mapping the input values to a smooth, non-linear range.
- The sigmoid function is commonly used in the last layer of a binary classification task, where the output represents the probability of belonging to a certain class.

In [ ]:
import math

In [ ]:
def sigmoid(z):
  return 1/(1+math.exp(-z))
sigmoid(1)

<span style="color:brown"> **Cannot pass array as an arguement**</span>

Give it a try to pass array to find sigmoid function of all the array elements.

In [ ]:
a=np.array([1,2,3])
sigmoid(a)

In [ ]:
def sigmoid(z):
  return 1/(1+np.exp(-z))

In [ ]:
# Example
x = np.array([-1, 0, 1])
output = sigmoid(x)
print(output)

In [ ]:
w = np.array([[0.1124579], [0.23106775]])
b = -0.3
X = np.array([[1., -1.1, -3.2],[1.2, 2., 0.1]])
A=sigmoid(np.dot(w.T,X)+b)
print(A)

## Broadcasting Example

In [ ]:
a=np.arange(12).reshape(4,3)
b=np.arange(10,22).reshape(4,3)
c=a*b
print(c)

In [ ]:
a=np.random.randn(3,4)
b=np.random.randn(4,1)
c=a+b.T
print("Shape of a+b.T ",c.shape)
c=a.T+b
print("Shape of a.T+b ",c.shape)

In [ ]:
a=np.random.randn(256,15)
b=np.random.randn(15,5)
c=np.dot(a,b)
c.shape

In [ ]:
percent=100*x/sum
print(percent)

In [ ]:
x = np.array([18, 2, 5, 3, 20]).reshape(5,1)
y = np.array([9, 14, 15, 3, -200]).reshape(5,1)
z=100*(abs(y-x))/x
print(z)

if x is a vector, then a Python operation such as $s = x + 3$ or $s = \frac{1}{x}$ will output s as a vector of the same size as x.

In [ ]:
print(a)
b=a+3
print(b)
b=b*7
print(b)

##Ploting a Sigmoid Function

In [ ]:
import matplotlib.pyplot as plt

- use `plt.plot()` to plot the z values against the sigmoid function values (y).
- `plt.title()` adds a title to the plot
- `plt.xlabel()` and `plt.ylabel()` label the x and y axes
- `plt.grid(True)` enable the grid
- Finally the plot is displayed `plt.show()`

In [ ]:
# Generate z values
z = np.linspace(-10, 10, 100)

# Compute sigmoid function for each z value
y = sigmoid(z)

# Plot the sigmoid function
plt.plot(z, y)
plt.title('Sigmoid Function')
plt.xlabel('z')
plt.ylabel('sigmoid(z)')
plt.grid(True)
plt.show()

##ReLU (Rectified Linear Unit)

- It takes an input value x and returns x if it is positive, and 0 otherwise.
- The ReLU function introduces non-linearity to the network by mapping negative values to 0, while leaving positive values unchanged.
- ReLU is a popular choice due to its simplicity and ability to mitigate the vanishing gradient problem.

In [ ]:
def relu(x):
    return np.maximum(0, x)

In [ ]:
# Let us consider the three observations
x = np.array([-1, 0, 1])
output = relu(x)
print(output)

In [ ]:
# Generate z values
z = np.linspace(-10, 10, 100)

# Compute ReLU function for each z value
y = relu(z)

# Plot the ReLU function
plt.plot(z, y)
plt.title('ReLU Function')
plt.xlabel('z')
plt.ylabel('relu(z)')
plt.grid(True)
plt.show()

##Softmax

- The softmax function is commonly used in multi-class classification tasks.
- Given an input vector x, the softmax function computes the probabilities for each class by exponentiating and normalizing the values.
- The softmax function is defined as follows:

$$P(C_i) = \frac {e^{z_i}}{\sum_{j=1}^C{e^{z_j}}}$$

- The output of the softmax function is a probability distribution, ensuring that the sum of the probabilities across all classes is equal to 1.

In [ ]:
def softmax(x, dim):
    x_exp=np.exp(x)
    if(dim>1):
      x_sum=np.sum(x_exp, axis=1).reshape(x.shape[0],1)
    else:
      x_sum=np.sum(x_exp)
    #print(x_sum)
    return x_exp/x_sum

In [ ]:
x = np.array([[9, 2, 5, 0, 0], [7, 5, 0, 0 ,0], [7, 5, 0, 0 ,0]]).T
print(x.shape)
print(x)
s=softmax(x, 2)
print(s)

In [ ]:
# Generate x values
x = np.linspace(-10, 10, 100)

# Compute Softmax function for each x value
y = softmax(x,1)

print(np.sum(y))
print(y)

# Plot the Softmax function
plt.plot(x, y)
plt.title('Softmax Function')
plt.xlabel('x')
plt.ylabel('softmax(x)')
plt.grid(True)
plt.show()

## np.sum()

In [155]:
a = np.array([[9, 2, 5, 3, 10], [7, 5, 10, 2 ,6], [17, 1, 10, 20 ,10]])

In [162]:
a.sum() #output the sum of all the elements

117

In [160]:
a.sum(axis=0) #output the row - axis 0 [Sum of each column]

array([33,  8, 25, 25, 26])

In [158]:
np.sum(a,axis=0)


array([33,  8, 25, 25, 26])

In [161]:
a.sum(axis=1) #output the column axis 1 [Sum of each row]

array([29, 30, 58])

##Mean Squared Error (MSE) Loss Function

Mean Squared Error (MSE) Loss Function:
- The Mean Squared Error (MSE) loss function is widely used for regression problems.
- It calculates the average squared difference between the predicted values and the true values.
- For a set of m predictions $y_{pred}$ and corresponding true values $y_{true}$, the MSE loss is computed as:

$$L_{mse}(\hat{y},y) = \sum_{i=0}^m( \hat{y}^{(i)}-y^{(i)})^2$$

- The MSE loss penalizes larger errors more than smaller errors due to the squaring operation.
- Minimizing the MSE loss encourages the model to produce predictions that are closer to the true values.

In [ ]:
def mse_loss(y, yhat):
  loss = np.dot(abs(y-yhat).T, abs(y-yhat))/y.shape[0]
  #Note that dor product gives you onle scalar.
  # We have used y.shape[0] to calculate mean
  #loss=np.mean((y - yhat) ** 2)
  return loss

In [ ]:
# Consider an example for three predictions
y_true = np.array([1, 2, 3, 4])
y_pred = np.array([1.5, 2.3, 3.2, 3.9])
#Try the below statement to show the broadcasting
#y_pred = np.array([1.5])
#Note that the program will throw an error if the shape of both
#y is not same except when either y_pred or y_true is one to facilitate the broadcating
loss = mse_loss(y_true, y_pred)
print(loss)

In [ ]:
def mse_loss(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2)

# Generate y_true values
y_true = np.array([2,3,4,6])

# Generate a range of y_pred values
y_pred = np.linspace(-2, 6, 8)

# Compute MSE loss for each y_pred value
loss = [mse_loss(y_true, y) for y in y_pred]

#Broadcast the y_pred in the mse_loss function to all the elements of y_true.
#You can change the number of elements in the y_true from 1 to 10 (say)

# Plot the MSE loss curve
plt.plot(y_pred, loss)
plt.title('Mean Squared Error (MSE) Loss')
plt.xlabel('Predicted Values (y_pred)')
plt.ylabel('Loss')
plt.grid(True)
plt.show()

- [...]: This is a list comprehension, which is a concise way to create a new list by iterating over a sequence (in this case, the y_pred values) and performing a specific operation for each element.

- The list comprehension loss = [mse_loss(y_true, y) for y in y_pred] iterates over each y value in y_pred, computes the Mean Square Error loss using mse_loss(y_true, y), and stores the results in the loss list.

##Binary Cross-Entropy Loss Function

- The Binary Cross-Entropy loss function is commonly used for binary classification problems.
- It measures the dissimilarity between the predicted probabilities and the true binary labels.
- For a set of m predictions y_pred and corresponding true labels y_true, the Binary Cross-Entropy loss is computed as:


$$L_{BCE} = -\frac{1}{m} \sum_{i=0}^m(ylog(\hat{y}) + (1 - y)log(1 - \hat{y}))$$

- The BCE loss penalizes models that have large differences between the predicted probabilities and the true labels.
- Minimizing the BCE loss encourages the model to assign higher probabilities to the correct class.

In [ ]:
def binary_cross_entropy(y_true, y_pred):
    return -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))


In [ ]:
y_true = np.array([0, 1, 1])
y_pred = np.array([0.3, 0.9, 0.7])
loss = binary_cross_entropy(y_true, y_pred)
print(loss)

In [ ]:
# Generate y_true and y_pred values
y_true = np.array([1, 0, 1, 0, 1])
y_pred = np.linspace(0.01, 0.99, 100)

# Compute Cross-Entropy loss for each y_true and y_pred pair
loss = [binary_cross_entropy(y_true, y) for y in y_pred]

# Plot the Cross-Entropy loss
plt.plot(y_pred, loss)
plt.title('Cross-Entropy Loss')
plt.xlabel('Predicted Probability (y_pred)')
plt.ylabel('Loss')
plt.grid(True)
plt.show()

##Categorical Cross-Entropy Loss Function

- The Categorical Cross-Entropy loss function is commonly used for multi-class classification problems.
- It measures the dissimilarity between the predicted class probabilities and the true class labels.
- For a set of m predictions y_pred and corresponding true labels y_true, the Categorical Cross-Entropy loss is computed as:

$$L_{CCE} = -\frac{1}{m} \sum (y) log(\hat{y})$$

- The CCE loss penalizes models that have low probabilities for the correct class.
- Minimizing the CCE loss encourages the model to assign higher probabilities to the correct classes.

#Linear Algebra Functions

##Normalization

Row Normalization is done by dividing each element of row of a given vector x by its norm based on row.

It is changing x to $ \frac{x}{\| x\|} $.

We get a column vector of norm if we take the square root of the sum of squares of each row elements. Then divide each row by its norm to normalize rows.


$$\| x\| = \text{np.linalg.norm(x, axis=1, keepdims=True)}$$

With `keepdims=True` the result will broadcast correctly against the original x.

`axis=1` means you are going to get the norm in a row-wise manner. If you need the norm in a column-wise way, you would need to set `axis=0`.

In [ ]:
x = np.array([[0, 3, 4],[1, 6, 4]])
x_norm=np.linalg.norm(x, axis=1, keepdims=True)
x=x/x_norm
print("Norm ", x_norm, "\nnormalizeRows(x) = ", x)

##Determinant and Inverse

In [177]:
x = np.array([[0, 3, 4],[1, 6, 4], [3,2,7]])

In [ ]:
np.linalg.det(x)

In [ ]:
np.linalg.inv(x)